[[linux]]
names = [ 'alacritty', 'helix', 'sway', 'joshuto' ]
to = '~/.config'

[[linux]]
names = [ '.gitconfig', '.profile', '.tmux.conf' ]
to = '~/'

[[linux]]
names = [ 'cargo.toml' ]
to = '~/.cargo'
rename = 'config.toml'
