[[user]]
names = ['alacritty', 'helix', 'sway', 'gtk-3.0', 'fontconfig', 'fcitx5']
to = '~/.config'

[[user]]
names = ['.gitconfig', '.profile', '.tmux.conf']
to = '~/'

[[system]]
names = ['greetd']
to = '/etc'
