#!/bin/sh

# Exit on any error
set -e

# Check if sudo is available
command -v sudo > /dev/null 2>&1 || { echo >&2 "The script requires 'sudo' but it's not installed.  Aborting."; exit 1; }

# Function to add a user to groups if not already added
add_user_to_group() {
    for group in "$@"; do
        if ! id -nG "$USER" | grep -qw "$group"; then
            sudo adduser "$USER" "$group"
        fi
    done
}

# Function to install packages
install_packages() {
    for package in "$@"; do
        if ! apk info -e "$package" > /dev/null 2>&1; then
            sudo apk add "$package"
        fi
    done
}

# Update and upgrade packages
echo "Updating and upgrading packages..."
sudo apk update && sudo apk upgrade

# Install Development Essentials
echo "Installing Development Essentials..."
install_packages build-base cmake openssl-dev git fontconfig-dev

# Install Audio/Video related packages
echo "Installing Audio/Video related packages..."
install_packages pulseaudio linux-firmware-amdgpu mesa mesa-dri-gallium mesa-va-gallium mesa-vulkan-ati

# Install Wayland/Sway related packages
echo "Installing Wayland/Sway related packages..."
install_packages wayland xwayland wl-clipboard sway swaylock swaybg swayidle udev dbus seatd cmd:seatd-launch

# Install Developer tools
echo "Installing Developer tools..."
install_packages redis rust-analyzer neovim ripgrep rustup nodejs yarn sccache

# Install Applications
echo "Installing Applications..."
install_packages firefox alacritty tmux font-jetbrains-mono-nerd

# Install elogind
echo "Installing elogind..."
install_packages elogind
sudo rc-update add elogind default
sudo service elogind start

# Install rust
echo "Installing Rust..."
rustup-init -y --default-toolchain nightly 
. "$HOME/.cargo/env"
. "$HOME/.alpine/dotfiles/.profile"

# Install cargo binaries
echo "Installing Cargo binaries..."
cargo install kickoff cargo-leptos cargo-watch tmux-sessionizer --locked

# Setup services
echo "Setting up services..."
echo amdgpu | sudo tee -a /etc/modules
echo fbcon | sudo tee -a /etc/modules
sudo setup-devd udev
echo $(sudo dbus-uuidgen) | sudo tee /var/lib/dbus/machine-id >/dev/null
sudo rc-update add dbus
sudo rc-update add seatd default
sudo rc-service dbus start

# Add user to groups
echo "Adding user to groups..."
add_user_to_group input video seat

# Link dotfiles
echo "Linking dotfiles..."
mkdir -p ~/.config

# Sway
rm -rf ~/.config/sway
ln -sf $DOT/sway ~/.config/sway

# Alacritty
rm -rf ~/.config/alacritty
ln -sf $DOT/alacritty ~/.config/alacritty

# Neovim
rm -rf ~/.config/nvim
ln -sf $DOT/nvim ~/.config/nvim

# Dotfiles
ln -sf $DOT/.tmux.conf ~/.tmux.conf
ln -sf $DOT/.gitconfig ~/.gitconfig
ln -sf $DOT/.profile ~/.profile

echo "Installation completed!"
