#!/bin/sh

# Exit on any error
set -e

# Check if sudo is available
command -v sudo > /dev/null 2>&1 || { echo >&2 "The script requires 'sudo' but it's not installed.  Aborting."; exit 1; }

# Update and upgrade packages
sudo apk update && sudo apk upgrade

# Function to add a user to groups if not already added
add_user_to_group() {
    for group in "$@"; do
        if ! id -nGz "$USER" | grep -qzxF "$group"; then
            sudo adduser $USER $group
        fi
    done
}

# Install packages
install_packages() {
    for pkg in "$@"; do
        if ! apk info -e "$pkg" >/dev/null 2>&1; then
            sudo apk add $pkg
        fi
    done
}

# Install Development Essentials
install_packages \
    build-base \
    cmake \
    openssl-dev \
    python3 \
    curl \
    wget \
    tar \
    git \
    fontconfig-dev

# Install XCB-related packages
install_packages \
    xcb-util-dev \
    xcb-util-renderutil-dev \
    xcb-util-image-dev

# Install Audio/Video related packages
install_packages \
    pulseaudio \
    linux-firmware-amdgpu \
    mesa \
    mesa-dri-gallium \
    mesa-va-gallium

# Install Wayland/Sway related packages
install_packages \
    wayland \
    xwayland \
    wl-clipboard \
    sway \
    swaylock \
    swaybg \
    swayidle \
    udev \
    dbus \
    seatd \
    cmd:seatd-launch

# Install Developer tools
install_packages \
    neovim \
    ripgrep \
    mprocs \
    rustup \
    nodejs \
    yarn \
    npm \
    lua-language-server \
    stylua \
    docker \
    docker-cli-compose

# Install Applications
install_packages \
    firefox-developer-edition \
    ncspot \
    alacritty \
    tmux \
    font-jetbrains-mono-nerd

# Install node packages
yarn global add typescript typescript-language-server

# Setup services
echo amdgpu | sudo tee -a /etc/modules
echo fbcon | sudo tee -a /etc/modules
sudo setup-devd udev
echo $(sudo dbus-uuidgen) | sudo tee /var/lib/dbus/machine-id >/dev/null
sudo rc-update add dbus
sudo rc-update add seatd default

# Add user to groups
add_user_to_group input video seat

# Setup rust
rustup-init -y --default-toolchain nightly

# Install cargo binaries
cargo install kickoff --locked
