#!/bin/sh

# Check if the correct number of arguments is provided
if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <source_directory> <destination_directory>"
  exit 1
fi

src_dir="$1"
dest_dir="$2"

find "$src_dir" -mindepth 1 -type f -or -type l | while IFS= read -r src_file; do
  relative_path="${src_file#$src_dir/}"
  dest_file="$dest_dir/$relative_path"
  dest_parent="$(dirname "$dest_file")"

  # Create parent directories if they don't exist
  mkdir -p "$dest_parent"

  # Create the symbolic link
  ln -sf "$src_file" "$dest_file"
done
