#!/bin/sh

sudo setup-devd

# Install development essentials
echo "Installing development essentials..."
sudo apk add build-base cmake libxkbcommon-dev libxkbfile-dev libressl-dev

# Install firmware
echo "Installing firmware"
sudo apk add linux-firmware-amdgpu mesa mesa-dri-gallium mesa-va-gallium mesa-vulkan-ati
echo amdgpu | sudo tee -a /etc/modules
echo fbcon | sudo tee -a /etc/modules

# Install pipewire
echo "Installing pipewire..."
sudo apk add wireplumber pipewire pipewire-pulse

# Install xdg
echo "Installing xdg..."
sudo apk add xdg-user-dirs xdg-desktop-portal xdg-desktop-portal-wlr
xdg-user-dirs-update

# Install wayland
echo "Installing wayland..."
sudo apk add wlroots wayland xwayland wl-clipboard

# Install sway
echo "Installing sway..."
sudo apk add sway swaylock swaybg swayidle

# Install rust
echo "Installing rust..."
sudo apk add rustup sccache
rustup-init -y --default-toolchain nightly
. "$HOME/.cargo/env"
rustup component add rust-analyzer
ln -sf $HOME/.rustup/toolchains/nightly-x86_64-unknown-linux-musl/bin/rust-analyzer \
  $HOME/.cargo/bin/rust-analyzer

# Install cargo binaries
echo "Installing cargo binaries..."
cargo install kickoff dotlink --locked

# Install node/yarn
echo "Installing node/yarn..."
sudo apk add nodejs-current yarn
yarn global add \
  typescript \
  @biomejs/biome \
  typescript-language-server \
  vscode-langservers-extracted \
  @tailwindcss/language-server

# Install fonts
echo "Installing fonts..."
sudo apk add fontconfig-dev font-jetbrains-mono-nerd font-ipa font-noto
fc-cache -fv

# Install languages
echo "Installing languages..."
sudo apk add fcitx5 fcitx5-anthy fcitx5-anthy-lang 

# Install user applications
echo "Installing user applications..."
sudo apk add firefox alacritty tmux grim grimshot mpv imv obs-studio helix ripgrep taplo

# Install dbus
#
# D-Bus is a message bus system that provides a mechanism for inter-process communication.
#
# Some services rely on a D-Bus session instance or expect it by default (including Pipewire).
# Other processes will only be able to communicate with these services if d-bus is running. 
echo "Installing D-Bus..."
sudo apk add dbus dbus-openrc
sudo rc-update add dbus default
echo $(sudo dbus-uuidgen) | sudo tee /var/lib/dbus/machine-id >/dev/null

# Install elogind
#
# elogind is a login manager and provides support for
# - setting up necessary permissions for the desktop environment or window manager
# - handling poweroff, reboot, suspend and hibernate via loginctl command
echo "Installing elogind..."
sudo apk add elogind
sudo rc-update add elogind default

# Install polkit
#
# Polkit is used for authentication. Without it some things may not function.
echo "Installing polkit..."
sudo apk add polkit polkit-elogind
sudo rc-update add polkit default

# Install greetd
#
# greetd acts as a system service that manages user sessions and provides a way for users
# to log into their system or start new sessions.
echo "Installing greetd..."
sudo apk add greetd greetd-wlgreet
sudo rc-update add greetd default
# Remove default greetd configuration
sudo rm -rf /etc/greetd

# Link user dotfiles
mkdir -p ~/.config
rm -rf ~/.profile
dotlink -p user

# Link system dotfiles
sudo dotlink -p system

# Ensure greetd permissions
sudo chmod -R go+r /etc/greetd
sudo addgroup greetd video
sudo addgroup greetd input

echo "Installation completed!"
