## -- Language Server Config --

[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]

## -- Languages--

[[language]]
name = "sql"
language-servers = ["sql-language-server"]

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "javascript"
language-servers = [{ name = "typescript-language-server" }, "biome"]
auto-format = true

[[language]]
name = "typescript"
language-servers = [{ name = "typescript-language-server" }, "biome"]
auto-format = true

[[language]]
name = "tsx"
auto-format = true
language-servers = [{ name = "typescript-language-server" }, "biome"]

[[language]]
name = "jsx"
auto-format = true
language-servers = [{ name = "typescript-language-server" }, "biome"]

[[language]]
name = "json"
language-servers = [{ name = "vscode-json-language-server" }, "biome"]
