#!/bin/sh

# Nord theme colors
COLOR1=#d8dee9
COLOR2=#eceff4

get_cpu_usage() {
    # Print the average CPU usage over the last 1 minute
    # We use awk to get the first value from the output of uptime, which is the 1-minute load average
    echo "CPU: $(uptime | awk -F'[a-z]:' '{ print $2}' | cut -f1 -d,)"
}

get_ram_usage() {
    # Print the percentage of used RAM
    # We use free and awk to calculate the percentage of used memory
    echo "RAM: $(free | awk '/Mem/{printf("%.2f%"), $3/$2 * 100.0}')"
}

get_disk_usage() {
    # Print the percentage of used disk space on the root partition
    # We use df and awk to calculate the percentage of used disk space
    echo "Disk: $(df / | awk 'NR==2 {print $5}')"
}

while true; do
    cpu_usage=$(get_cpu_usage)
    ram_usage=$(get_ram_usage)
    disk_usage=$(get_disk_usage)
    date_output=$(date +'%a %-d %b %H:%M')

    echo "<span font_weight=\"600\"><span foreground=\"${COLOR1}\">$cpu_usage</span>   <span foreground=\"${COLOR1}\">$ram_usage</span>   <span foreground=\"${COLOR1}\">$disk_usage</span>   <span foreground=\"${COLOR1}\">$date_output</span></span>"
    sleep 5
done
