# [language-server.rust-analyzer.config.rustfmt]
# overrideCommand = ["leptosfmt", "--stdin", "--rustfmt"]

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "hcl"
auto-format = true
language-servers = ["terraform-ls"]

[[language]]
name = "html"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "html"] }

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true
