[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = { typescript = { tsdk = "/usr/local/lib/node_modules/typescript/lib" }, environment = "node" }

[[language]]
name = "astro"
auto-format = true
language-servers = [ "astro-ls" ]
